# Generated by Django 5.2.3 on 2026-05-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nssapp', '0004_rename_description_notes_notesdesc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'nsuser'), (1, 'admin')], default=1, max_length=50),
        ),
    ]
