services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: nsspythondb
      MYSQL_ROOT_PASSWORD: root123

    ports:
      - "3307:3306"

  web:
    build: .
    restart: always

    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - db